UPDATE INVOICE SET INV_TAX                                                             =
IIF(INV_SUBTOTAL IS NOT NULL, INV_SUBTOTAL * 0.08, 0),INV_TOTAL =
IIF(INV_SUBTOTAL IS NOT NULL, INV_SUBTOTAL + (INV_SUBTOTAL * 0.08), 0)
WHERE INV_TAX IS NULL OR INV_TOTAL IS NULL;