-- Using SQL CASE statements
UPDATE INVOICE SET INV_TAX                                                             =
CASE WHEN INV_SUBTOTAL IS NOT NULL THEN INV_SUBTOTAL * 0.08 ELSE 0 END,
INV_TOTAL = CASE WHEN INV_SUBTOTAL IS NOT NULL THEN INV_SUBTOTAL + (INV_SUBTOTAL * 0.08) ELSE 0 END
WHERE INV_TAX IS NULL OR INV_TOTAL IS NULL;
SELECT * FROM INVOICE;

-- Using SQLServer IIF function to simplify the CASE statements
UPDATE INVOICE SET INV_TAX                                                             =
IIF(INV_SUBTOTAL IS NOT NULL, INV_SUBTOTAL * 0.08, 0), INV_TOTAL =
IIF(INV_SUBTOTAL IS NOT NULL, INV_SUBTOTAL + (INV_TAX), 0)
WHERE INV_TAX IS NULL OR INV_TOTAL IS NULL;