CREATE TRIGGER trg_line_total on LINE
AFTER INSERT AS
BEGIN
    UPDATE LINE SET LINE_TOTAL = LINE.LINE_UNITS * LINE.LINE_PRICE
    FROM LINE
    JOIN INSERTED ON LINE.LINE_NUMBER = INSERTED.LINE_NUMBER;
END