CREATE PROCEDURE prc_inv_amounts @invNumber INT AS
BEGIN
    UPDATE INVOICE
    SET INV_SUBTOTAL = (SELECT SUM(LINE_TOTAL) FROM LINE WHERE INV_NUMBER = @invNumber),
    INV_TAX = INV_SUBTOTAL * 0.08,
    INV_TOTAL = INV_SUBTOTAL + INV_TAX
    WHERE INV_NUMBER = @invNumber;
END