CREATE PROCEDURE prc_cus_balance_update @invNum INT AS
BEGIN
    DECLARE @totalInv NUMERIC(10,2)
    SET @totalInv = (SELECT SUM(INV_TOTAL) FROM INVOICE WHERE INV_NUMBER = @invNum);
    UPDATE CUSTOMER SET CUS_BALANCE = CUS_BALANCE + @totalInv
        WHERE CUS_CODE = (SELECT CUS_CODE FROM INVOICE WHERE INV_NUMBER = @invNum);
END