SELECT SUM(CUS_BALANCE) AS 'Total Balance', MIN(CUS_BALANCE) AS 'Minimum Balance', MAX(CUS_BALANCE) AS 'Maximum Balance', AVG(CUS_BALANCE) AS 'Average Balance'
FROM CUSTOMER
WHERE CUS_CODE NOT IN (
    SELECT DISTINCT CUS_CODE
    FROM INVOICE);