CREATE TABLE EMPLOYEE_SHIFT (
   EMPLOYEE_ID INT NOT NULL,
   SHIFT_ID INT NOT NULL,
   PRIMARY KEY (EMPLOYEE_ID, SHIFT_ID),
   FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMP_ID),
   FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT (SHIFT_ID)
);
