CREATE TABLE EMPLOYEE_DEPARTMENT (
    EMP_ID INT,
    DEPT_ID INT,
    PRIMARY KEY (EMP_ID, DEPT_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID)
);
