CREATE TABLE WRITTEN_WARNING (
  WW_ID INT PRIMARY KEY,
  WW_DATE DATE,
  WW_OFFENCE VARCHAR(255),
  WW_LEVEL VARCHAR(50),
  WW_STATUS VARCHAR(50),
  WW_COMMENTS VARCHAR(255),
  EMP_ID_ISSUER INT,
  EMP_ID_RECEIVER INT,
  CONSTRAINT FK_EMP_ISSUER FOREIGN KEY (EMP_ID_ISSUER) REFERENCES EMPLOYEE(EMP_ID),
  CONSTRAINT FK_EMP_RECEIVER FOREIGN KEY (EMP_ID_RECEIVER) REFERENCES EMPLOYEE(EMP_ID)
);
