SELECT PROJECT.PROJ_NAME, PROJECT.PROJ_VALUE, PROJECT.PROJ_BALANCE, EMPLOYEE.EMP_LNAME, EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_INITIAL, EMPLOYEE.JOB_CODE, JOB.JOB_DESCRIPTION, JOB.JOB_CHG_HOUR
FROM PROJECT JOIN EMPLOYEE ON PROJECT.EMP_NUM = EMPLOYEE.EMP_NUM
JOIN JOB ON EMPLOYEE.JOB_CODE = JOB.JOB_CODE;